/* eslint-disable */
// @ts-nocheck
// biome-ignore lint: disable
// oxlint-disable
// ------
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399

export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    EditorLayout: typeof import('./src/components/layout/EditorLayout.vue')['default']
    EditorToolbar: typeof import('./src/components/toolbar/EditorToolbar.vue')['default']
    IMdiHome: typeof import('~icons/mdi/home')['default']
    MarkdownEditor: typeof import('./src/components/editor/MarkdownEditor.vue')['default']
    MarkdownPreview: typeof import('./src/components/preview/MarkdownPreview.vue')['default']
  }
}
